### ISSUE TITLE
Different prefix based off the time of day

### ISSUE THREAD

**Issue by gleich** [jameslan/vscode-yaclock#1]
I love for the emoji to change based of the time of the day. Below is an example:
Morning: ☀️
Afternoon:  ☕️
Night: 🦉

**Comment by jameslan** [comment]
This would be fun! Thanks for the idea!

**Comment by gleich** [comment]
Can I do it?

**Comment by jameslan** [comment]
Sure.

But I'm hesitating the elegant design for this.

I wish it could be generic, which means it should allow people using 12 clock emojis to create an analog clock
or someone wants it to appear in the postfix etc. And the complexity introduced by the flexibility should not affect the normal user's setting, who just wants a plain clock.

Any idea?

Did you check [powertools](https://marketplace.visualstudio.com/items?itemName=ego-digital.vscode-powertools)? It might be generic enough but need the user to learn more

**Comment by gleich** [comment]
I think that this extension serves as a good minimalist clock and a clock with changing emojis would be better as its own extension. Because of this, I am going to make my own extension!
