### ISSUE TITLE
yaclock 1.0.2 status ends with `: [object Object]`

### ISSUE THREAD

**Issue by fungiboletus** [jameslan/vscode-yaclock#3]
Since the version `1.0.2`, the status ends with `: [object Object]`. Reverting to `1.0.1` fixes the issue.

I use VSCode `1.88.0`.

<img width="138" alt="image" src="https://github.com/jameslan/vscode-yaclock/assets/45740/222388da-20d1-4386-ba3b-c0915be5d2b1">

**Comment by jameslan** [comment]
Oops, some local changes were escaped when publishing.
Please update to 1.0.3

**Comment by fungiboletus** [comment]
Thanks !
